version: '3.1'

services:

  ########################## MAIN ##############################

  nginx:
    image: nginx:1.17.3-alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./../:/var/www/html
    links:
      - php
    ports:
      - 127.0.0.1:8080:80

  php:
    build:
      context: ./
      dockerfile: ./php.dock
    restart: on-failure
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      DEV: 'test'
    links:
      - mysql
      - redis
      - rabbitmq
    volumes:
      - ./../:/var/www/html

  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./../database:/docker-entrypoint-initdb.d

  redis:
    image: redis:4.0.10-alpine
    restart: on-failure
    ports:
      - 127.0.0.1:6379:6379

  rabbitmq:
    image: rabbitmq:3.7.7-alpine
    restart: on-failure
    hostname: localhost
    environment:
      RABBITMQ_DEFAULT_USER: 'test'
      RABBITMQ_DEFAULT_PASS: 'test'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - 127.0.0.1:15672:15672
      - 127.0.0.1:5672:5672

  ########################## TOOLS ##############################

  adminer:
    image: adminer
    restart: on-failure
    links:
      - mysql
    ports:
      - 127.0.0.1:8081:8080

